### ISSUE TITLE
With Etherpad-lite latest, ep_adminpads does not display a list of my pads

### ISSUE THREAD

**Issue by feoh** [spcsser/ep_adminpads#26] opened 2015-07-28 13:49 UTC
Tried it across two different etherpad-lite installs and a couple of different node.js versions but thus far no dice.

Unfortunately I have no diagnostics to offer because I don't see any errors in the log.

Here's the Troubleshooting Information issued by Etherpad-lite:
---
```
Etherpad version

Version number: 1.5.6

Git sha: 5c531ee

Installed plugins

ep_adminpads
ep_codepad, ep_etherpad-lite
Installed parts

ep_etherpad-lite/swagger
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/webaccess
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/static
ep_etherpad-lite/express
ep_codepad/ep_codepad_cursortrace
ep_codepad/ep_codepad_themes
ep_codepad/ep_codepad_keypress_handler
ep_codepad/ep_codepad_trace_braces
ep_codepad/ep_codepad_themed_syntaxhighlighting
ep_codepad/ep_codepad_buttons_feedback
ep_codepad/ep_padsearch
ep_codepad/ep_codepad_defaults
ep_codepad/ep_codepad_fileload
ep_codepad/ep_codepad_search
ep_codepad/ep_codepad_logview
ep_codepad/ep_codepad_fileview
ep_codepad/ep_codepad_filerunner
ep_codepad/ep_codepad_filestaticview
ep_codepad/ep_codepad_filetree
ep_codepad/ep_codepad_play
ep_codepad/ep_codepad_foldersupport
ep_codepad/ep_codepad_auth
ep_codepad/ep_codepad_index_page
ep_adminpads/ep_adminpads
Installed hooks

Server side hooks

expressCreateServer
ep_etherpad-lite/node/hooks/express/swagger:expressCreateServer from ep_etherpad-lite/swagger
expressCreateServer
ep_etherpad-lite/node/hooks/express/adminsettings:expressCreateServer from ep_etherpad-lite/adminsettings
expressCreateServer
ep_etherpad-lite/node/hooks/express/adminplugins:expressCreateServer from ep_etherpad-lite/adminplugins
expressCreateServer
ep_etherpad-lite/node/hooks/express/admin:expressCreateServer from ep_etherpad-lite/admin
expressCreateServer
ep_etherpad-lite/node/hooks/express/tests:expressCreateServer from ep_etherpad-lite/tests
expressCreateServer
ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer from ep_etherpad-lite/socketio
expressCreateServer
ep_etherpad-lite/node/hooks/express/errorhandling:expressCreateServer from ep_etherpad-lite/errorhandling
expressCreateServer
ep_etherpad-lite/node/hooks/express/importexport:expressCreateServer from ep_etherpad-lite/importexport
expressCreateServer
ep_etherpad-lite/node/hooks/express/apicalls:expressCreateServer from ep_etherpad-lite/apicalls
expressCreateServer
ep_etherpad-lite/node/hooks/express/padreadonly:expressCreateServer from ep_etherpad-lite/padreadonly
expressCreateServer
ep_etherpad-lite/node/hooks/express/padurlsanitize:expressCreateServer from ep_etherpad-lite/padurlsanitize
expressCreateServer
ep_etherpad-lite/node/hooks/express/specialpages:expressCreateServer from ep_etherpad-lite/specialpages
expressCreateServer
ep_etherpad-lite/node/hooks/i18n:expressCreateServer from ep_etherpad-lite/i18n
expressCreateServer
ep_etherpad-lite/node/hooks/express/static:expressCreateServer from ep_etherpad-lite/static
expressCreateServer
ep_codepad/search:expressCreateSearchServer from ep_codepad/ep_codepad_search
expressCreateServer
ep_codepad/logview:expressCreateLogViewServer from ep_codepad/ep_codepad_logview
expressCreateServer
ep_codepad/fileview:expressCreateFileViewServer from ep_codepad/ep_codepad_fileview
expressCreateServer
ep_codepad/filerunner:expressCreateFileRunServer from ep_codepad/ep_codepad_filerunner
expressCreateServer
ep_codepad/filestatic:expressCreateFileStaticViewServer from ep_codepad/ep_codepad_filestaticview
expressCreateServer
ep_codepad/filetree:expressCreateFileTreeServer from ep_codepad/ep_codepad_filetree
expressCreateServer
ep_codepad/playserver:expressCreatePlayServer from ep_codepad/ep_codepad_play
expressCreateServer
ep_codepad/foldersupport:expressCreateFolderServer from ep_codepad/ep_codepad_foldersupport
expressCreateServer
ep_adminpads/index:registerRoute from ep_adminpads/ep_adminpads
socketio
ep_etherpad-lite/node/hooks/express/adminsettings:socketio from ep_etherpad-lite/adminsettings
socketio
ep_etherpad-lite/node/hooks/express/adminplugins:socketio from ep_etherpad-lite/adminplugins
socketio
ep_adminpads/index:socketio from ep_adminpads/ep_adminpads
expressConfigure
ep_etherpad-lite/node/hooks/express/webaccess:expressConfigure from ep_etherpad-lite/webaccess
createServer
ep_etherpad-lite/node/hooks/express:createServer from ep_etherpad-lite/express
restartServer
ep_etherpad-lite/node/hooks/express:restartServer from ep_etherpad-lite/express
eejsBlock_scripts
ep_codepad/themes_index:eejsBlock_scripts from ep_codepad/ep_codepad_themed_syntaxhighlighting
eejsBlock_scripts
ep_codepad/buttons from ep_codepad/ep_codepad_buttons_feedback
eejsBlock_styles
ep_codepad/themes_index:eejsBlock_styles from ep_codepad/ep_codepad_themed_syntaxhighlighting
eejsBlock_styles
ep_codepad/buttons from ep_codepad/ep_codepad_buttons_feedback
eejsBlock_timesliderStyles
ep_codepad/themes_index:eejsBlock_timesliderStyles from ep_codepad/ep_codepad_themed_syntaxhighlighting
eejsBlock_editbarMenuRight
ep_codepad/themes_index:eejsBlock_editbarMenuRight from ep_codepad/ep_codepad_themed_syntaxhighlighting
eejsBlock_editbarMenuLeft
ep_codepad/themes_index:eejsBlock_editbarMenuLeft from ep_codepad/ep_codepad_themed_syntaxhighlighting
eejsBlock_mySettings.dropdowns
ep_codepad/themes_index:eejsBlock_mySettings_dropdowns from ep_codepad/ep_codepad_themed_syntaxhighlighting
clientVars
ep_codepad/themes_index:clientVars from ep_codepad/ep_codepad_themed_syntaxhighlighting
handleMessage
ep_codepad/handleButtonMessage from ep_codepad/ep_codepad_buttons_feedback
handleMessage
ep_codepad/auth:handleMessage from ep_codepad/ep_codepad_auth
padCreate
ep_codepad:padCreate from ep_codepad/ep_codepad_fileload
padCreate
ep_adminpads/index:updatePads from ep_adminpads/ep_adminpads
authenticate
ep_codepad/auth from ep_codepad/ep_codepad_auth
eejsBlock_indexWrapper
ep_codepad/index_page from ep_codepad/ep_codepad_index_page
padRemove
ep_adminpads/index:updatePads from ep_adminpads/ep_adminpads
eejsBlock_adminMenu
ep_adminpads/index:eejsBlock_adminMenu from ep_adminpads/ep_adminpads
Client side hooks

handleClientMessage_CUSTOM
ep_codepad/static/js/cursortrace:handleClientMessage_CUSTOM from ep_codepad/ep_codepad_cursortrace
handleClientMessage_CUSTOM
ep_codepad/static/js/message:handleClientMessage_CUSTOM from ep_codepad/ep_codepad_buttons_feedback
aceKeyEvent
ep_codepad/static/js/cursortrace:aceKeyEvent from ep_codepad/ep_codepad_cursortrace
aceKeyEvent
ep_codepad/static/js/keypress:aceKeyEvent from ep_codepad/ep_codepad_keypress_handler
aceKeyEvent
ep_codepad/static/js/syntax:aceKeyEvent from ep_codepad/ep_codepad_themed_syntaxhighlighting
aceEditorCSS
ep_codepad/static/js/themes:aceEditorCSS from ep_codepad/ep_codepad_themes
aceInitInnerdocbodyHead
ep_codepad/static/js/themes:aceInitInnerdocbodyHead from ep_codepad/ep_codepad_themes
aceInitInnerdocbodyHead
ep_codepad/static/js/syntax:aceInitInnerdocbodyHead from ep_codepad/ep_codepad_themed_syntaxhighlighting
aceEditEvent
ep_codepad/static/js/tracebraces:aceEditEvent from ep_codepad/ep_codepad_trace_braces
acePostWriteDomLineHTML
ep_codepad/static/js/syntax:acePostWriteDomLineHTML from ep_codepad/ep_codepad_themed_syntaxhighlighting
disableAuthorColorsForThisLine
ep_codepad/static/js/syntax:disableAuthorColorsForThisLine from ep_codepad/ep_codepad_themed_syntaxhighlighting
postAceInit
ep_codepad/static/js/codepad_defaults:postAceInit from ep_codepad/ep_codepad_defaults
documentReady
ep_adminpads/static/js/admin/pads:documentReady from ep_adminpads/ep_adminpads
```

**Comment by LaKing** [comment] 2015-07-28 21:55
Indeed.

**Comment by spcsser** [comment] 2015-08-13 13:14
I'll look into this, but it won't probably be until end of next week.

**Comment by feoh** [comment] 2015-08-13 14:25
@spcsser Anytime you can take a look that would be fantastic. I don't know node at all or I'd do it myself and submit a PR.  I've been using restclient from emacs to delete old pads, which is kind of a drag :)

**Comment by spcsser** [comment] 2015-09-08 15:29
Could not reproduce this - tried the following:
1) latest etherpad from git, reinstalled ep_adminpads
2) tagged version 1.5.6 of etherpad, reinstalled ep_adminpads
2.1) installed ep_codepad

Is this still an issue?

**Comment by feoh** [comment] 2015-09-08 15:50
@spcsser Yes. I updated to the latest master of etherpad-lite, and none of my pads are showing up whyen I browse to /admin and choose "Manage Pads".

You can play with my instance if you like for debugging:

http://amicable.feoh.org/admin
(default admin username/password)

**Comment by Steffov** [comment] 2015-09-18 07:22
I can confirm this bug. I use the Etherpad version 1.5.7 (442f2a0) and see no pads under manage pads. No errors in the log file.

**Comment by Steffov** [comment] 2015-09-28 09:25
With the latest Etherpad update it seems to be fixed! :)

Version number: 1.5.7
Git sha: 9c8c3de

Now I can see and delete all the pads!

**Comment by spcsser** [comment] 2015-10-05 12:57
Apparently, this is an issue with ep_codepad. Could reproduce it and am currently investigating it - closing this and continuing on ticket #28.

**Closed by spcsser** 2015-10-05 12:58 UTC

**Comment by Steffov** [comment] 2015-10-05 14:46
Maybe it'll help you. I'm not using ep_codepad.
